// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qgopqjgnczeimbwsyxbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFnb3BxamduY3plaW1id3N5eGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNjM5MTMsImV4cCI6MjA1NzYzOTkxM30.Br0uaGw6PQgfxaPKs_5zJzmMOxyboDxRwOAfj1LHNvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);